version: 2

project_name: jsi

builds:
  - id: jsi
    main: ./cmd/jsi
    binary: jsi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: jsi-tui
    main: ./cmd/jsi-tui
    binary: jsi-tui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{- end }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"

release:
  github:
    owner: treytorrez
    name: jsi
